### ISSUE TITLE
How to generate Chinese images?

### ISSUE THREAD

**Issue by liuzhuang1024** [Jyouhou/UnrealText#1]

**Comment by longshangbang** [comment]
You can modiy line 44-85: https://github.com/Jyouhou/UnrealText/blob/2058ddd9bec026341549968179eee699f9c13b75/code/DataGenerator/TextPlacingModule.py#L44

I will make an easier interface shortly

**Comment by longshangbang** [comment]
The code has been updated

Please refer to the following instructions:

https://github.com/Jyouhou/UnrealText/blob/master/code/Tutorial-on-deployment.md#62-generate-data

and 

https://github.com/Jyouhou/UnrealText/blob/0156a62fb59eb53418565e824c489b5d48281313/code/DataGenerator/options.py#L23
