### ISSUE TITLE
What is counted as difficult text ?

### ISSUE THREAD

**Issue by mmmmmore** [Jyouhou/UnrealText#10]
Thanks for open sourcing data generation code. May I know your the intended usage on the flag `is_difficult` ? 

In the source code it is always set to be 0, this looks a bit confusing. Any additional explanation would be greatly appreciated !

**Comment by longshangbang** [comment]
Thanks!

It was intended to mark some potentially difficult text, such as text that are too small or text regions that are too dark. 

Later I found that it will draw down the generation speed (especially when we need to check if a text region is too dark). Besides, in my initial experiments with the EAST models, filtering out these difficult samples did not help. So I took off the code, and just leave this flag there.
