### ISSUE TITLE
Some characters are not supported by the fonts

### ISSUE THREAD

**Issue by mmmmmore** [Jyouhou/UnrealText#11]
Some characters seem to be unsupported by the fonts files and the 10 pixel rule doesn't seem to apply.

example file: `english/sub_101/labels/444.json`

Some unknown characters are rendered on the top left corner ( under Toun ) in the following image.
![444](https://user-images.githubusercontent.com/65213896/86566058-8fb41000-bf9b-11ea-82ff-9bf88564ffe9.jpg)

May I know if there's a good way to solve it ?

Thanks !

**Comment by longshangbang** [comment]
Maybe some fonts do not support some characters. 

Since the performance is still good enough, I haven't dealt with them yet. I will correct this part in the future. 

For now, you can just use the dataset as it is. The proportion should be very low.
