### ISSUE TITLE
Hello, can this be implemented directly in code without using the UE engine?

### ISSUE THREAD

**Issue by lifei1229** [Jyouhou/UnrealText#17]
Hello, can this be implemented directly in code without using the UE engine?

**Comment by longshangbang** [comment]
You can use the prebuilt binaries.

**Comment by lifei1229** [comment]
Thank you for your reply. I used the prebuilt binaries   and met another question: can it be implemented in ubuntu server?

**Comment by longshangbang** [comment]
It should be possible but not with the current code.
