### ISSUE TITLE
Is it normal after step2

### ISSUE THREAD

**Issue by zhangjx123** [Jyouhou/UnrealText#18]
![Screenshot from 2020-09-22 18-00-42](https://user-images.githubusercontent.com/38745800/93869021-da713880-fcfd-11ea-9906-07c5f7be4fe4.png)
Is it normal after step2? I find it is different from your figures.

**Comment by longshangbang** [comment]
Which version of UE4 are you using? 

Some scene models only fit certain versions.

**Comment by zhangjx123** [comment]
> Which version of UE4 are you using?
> 
> Some scene models only fit certain versions.

I just follow your guidance and do "git clone -b 4.22 --depth 1 https://github.com/EpicGames/UnrealEngine.git  "

**Comment by longshangbang** [comment]
Can you give me more information? It looks like the assets are not imported correctly. The error should be in step 1.

**Comment by zhangjx123** [comment]
> Can you give me more information? It looks like the assets are not imported correctly. The error should be in step 1.

Thank you for your kindness, I have found my error in step1.
