### ISSUE TITLE
I find that it is difficult to run the demo.

### ISSUE THREAD

**Issue by zhangjx123** [Jyouhou/UnrealText#19]
When it run to Line 72 in TexPlacingModule.py, error occurred as 'FileNotFoundError: [Errno 2] No such file or directory: '/home/eecbd/github_project/UnrealText_CVPR2020/GeneratedData/DataFraction_14/WordCrops/adjusted_text_box.txt''.
We can't find anywhere to save 'adjusted_text_box.txt' in your code, could you please help me solve this problem?

**Comment by longshangbang** [comment]
It's located here: https://github.com/Jyouhou/UnrealText/blob/dc8460a8dff37c61d5bf290b013674bb0c42d429/code/UnrealText/Source/UnrealCV/Private/Commands/ObjectHandler.cpp#L667

Another possible cause is that the connection to the executable is not successful. Please first check whether the connection works.

**Comment by zhangjx123** [comment]
> It's located here:
> 
> https://github.com/Jyouhou/UnrealText/blob/dc8460a8dff37c61d5bf290b013674bb0c42d429/code/UnrealText/Source/UnrealCV/Private/Commands/ObjectHandler.cpp#L667
> 
> Another possible cause is that the connection to the executable is not successful. Please first check whether the connection works.

I am confused about the way to start UE4 Engine  after run 'python3 run_generation.py --UnrealProjectName $SceneName --languages Latin'. Before, we try to start it in the backend following the guidance in http://docs.unrealcv.org/en/master/reference/model_zoo.html#rr.

**Comment by longshangbang** [comment]
"I am confused about the way to start UE4 Engine after run 'python3 run_generation.py --UnrealProjectName $SceneName --languages Latin'"

was the executable launched successfully?

**Comment by zhangjx123** [comment]
> "I am confused about the way to start UE4 Engine after run 'python3 run_generation.py --UnrealProjectName $SceneName --languages Latin'"
> 
> was the executable launched successfully?
yes. The command I used is "./UE4Editor /home/ziyan/PackagedEnvironment/RealisticRendering/Demo_RealisticRend/Demo_RealisticRend.uproject".
![Screenshot from 2020-10-17 23-00-34](https://user-images.githubusercontent.com/38745800/96344228-b6223500-10cc-11eb-8c2d-fff683699969.png)

**Comment by zhangjx123** [comment]
> "I am confused about the way to start UE4 Engine after run 'python3 run_generation.py --UnrealProjectName $SceneName --languages Latin'"
> 
> was the executable launched successfully?

Above is the command and screenshot. I am looking forward for your kind guidance.

**Comment by longshangbang** [comment]
The command you used only loads the demo project with the **UE editor.** 

However, you should launch the **binary** **executable** instead:

https://github.com/Jyouhou/UnrealText/blob/dc8460a8dff37c61d5bf290b013674bb0c42d429/code/DataGenerator/DataGeneratorModule.py#L194

**Comment by zhangjx123** [comment]
When I want to launch the binary executable in '../../../PackagedEnvironment/{UnrealProjectName}/Demo_RealisticRend/Binaries/Linux/Demo_RealisticRend' in terminal, it reports './Demo_RealisticRend: error while loading shared libraries: libApexCommonPROFILE.so: cannot open shared object file: No such file or directory' It is anything wrong?

**Comment by longshangbang** [comment]
Can you specify your environment?

**Comment by longshangbang** [comment]
"Demo_RealisticRend" is not a packaged executable. It can not be launched in this way. If you want to generate data, you should use packaged executables: https://github.com/Jyouhou/UnrealText/blob/master/ReleaseNote.md#4-packaged-scene-executables
