### ISSUE TITLE
How to extract the word image lebels from the UNREAL text?

### ISSUE THREAD

**Issue by zobeirraisi** [Jyouhou/UnrealText#21]
How you select the 3M word image from the 150 GB dataset?

**Comment by longshangbang** [comment]
In the paper, we mentioned that "We discard images with widths shorter than 32 pixels as they are too blurry, and obtain 4.1M word images in total. "

For the 3Mx3 experiment, I randomly select 3M from this 4.1M.

**Comment by zobeirraisi** [comment]
> In the paper, we mentioned that "We discard images with widths shorter than 32 pixels as they are too blurry, and obtain 4.1M word images in total. "
> 
> 
> 
> For the 3Mx3 experiment, I randomly select 3M from this 4.1M. 

Is it possible to share those extracted images?

**Comment by longshangbang** [comment]
> > In the paper, we mentioned that "We discard images with widths shorter than 32 pixels as they are too blurry, and obtain 4.1M word images in total. "
> > For the 3Mx3 experiment, I randomly select 3M from this 4.1M.
> 
> Is it possible to share those extracted images?

Sorry, I didn't keep those data after I left the company. 

I recommend that you filter out text that are too small. 

If it's possible, you can set the `FontSize ` flag and  generate a new dataset with larger text.
