### ISSUE TITLE
Can you share the word crop code

### ISSUE THREAD

**Issue by wushilian** [Jyouhou/UnrealText#23]
In the paper : "We crop from the proposed multilingual dataset. We discard images with widths shorter than 32 pixels as they are too blurry, and obtain 4.1M word images in total."
But I ended up with more than 7 million text line images.

**Comment by longshangbang** [comment]
How did you crop the text regions? Did you use axis-aligned boxes or quadrilaterals?

**Comment by wushilian** [comment]
@Jyouhou I use axis-aligned boxes，and only the rectangle with width and height greater than 32 is reserved

**Comment by longshangbang** [comment]
Thanks for the reply. 

Most text are highly oriented in the dataset. I filtered by the shortest edge of the quadrilaterals (not the axis-aligned boxes).

**Comment by wushilian** [comment]
@Jyouhou Can you share your wechat? It's more convenient to communicate

**Comment by longshangbang** [comment]
Sure. You can send your wechat account to my cmu email: shangbal@cs.cmu.edu
