### ISSUE TITLE
The character boxes on hook faces seems to be offset

### ISSUE THREAD

**Issue by GaroneHuang** [Jyouhou/UnrealText#24]
There seems to be offset of  character boxes on hook faces with high probability, shown in the following images.
This image is from English dataset Sub39 27.jpg
![image](https://user-images.githubusercontent.com/65281345/114528279-73a47400-9c7b-11eb-8055-d70aa3a71e38.png)
Only use perspective transformation to get the boxes may not work.

**Comment by longshangbang** [comment]
You are right -- on curved face, it would look weird. The ideal solution is to print characters one by one, but that would take a long time.

**Comment by GaroneHuang** [comment]
Thanks a lot for your answer. But how can I print characters one by one. I have read the source code and found that it only can put the images on adjusted text boxes generated by unrealcv, and the text boxes seem to be to large. How can I put a character image on a small box?

**Comment by GaroneHuang** [comment]
@Jyouhou Thanks a lot for your answer. But how can I print characters one by one. I have read the source code and found that it only can put the images on adjusted text boxes generated by unrealcv, and the text boxes seem to be to large. How can I put a character image on a small box?

**Comment by longshangbang** [comment]
With the current UnrealText implementation, printing characters are not enabled. It's too time consuming.
