### ISSUE TITLE
How to uncompress the bg_img.003.001

### ISSUE THREAD

**Issue by weinixuehao** [Jyouhou/UnrealText#26]
I was uncompressed the bg_img.003.001 to bg_img.003 with "7z" cmd tool, But bg_img.003 could not be uncompressed.

**Comment by longshangbang** [comment]
Hi, those bg_img.7z.00* files should be merged before uncompressing.

**Comment by longshangbang** [comment]
Or you can download them all, and double-click .001. 

That will uncompress them all together.
