### ISSUE TITLE
I did not find this documentation for vget /object/GetAdjusted

### ISSUE THREAD

**Issue by weinixuehao** [Jyouhou/UnrealText#27]
self.client.request(f'vget /object/GetAdjusted {num} {savepath}')
"error Can not find a handler for URI 'vget /object/GetAdjusted 11 /Users/imac-1/workspace/UnrealTextWorkDir/GeneratedData/DataFraction_10/WordCrops/adjusted_text_box.txt'"

**Comment by longshangbang** [comment]
Please specify your environment.

Did you launch those 3D environment binaries?
