### ISSUE TITLE
Issue with the labels file

### ISSUE THREAD

**Issue by RamanHacks** [Jyouhou/UnrealText#28]
In some files, the number of `cbox` and number of character in `text` doesn't match. For example: in `UnrealText/sub_5/labels/288.json`: no of cboxes are 32 while no. of characters are 33. Any way to resolve this?

**Comment by longshangbang** [comment]
Sorry for the late reply ---- I didn't notice this issue when I implemented it. 

If it's only a small proportion, please just discard them.
