### ISSUE TITLE
some imgs seem to be corrupted

### ISSUE THREAD

**Issue by aiboys** [Jyouhou/UnrealText#29]
Hi,
  Thanks for your open source dataset. But when I use Unrealtext dataset, I found some imgs corrupted. I referenced mmocr source code to pretrain my model, but it seems loading img meet error:
```python
            with open(img_name, 'rb') as f:
                img_buff = f.read()
            img = mmcv.imfrombytes(img_buff, IMREAD_COLOR)
```
accidently,  above code would meets error: cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'.  It seems the img file is corrupted. But I am not sure which one or ones corrupted (Debugging and finding)

**Comment by longshangbang** [comment]
Can you try:

```
try:
  with open(img_name, 'rb') as f:
    img_buff = f.read()
  img = mmcv.imfrombytes(img_buff, IMREAD_COLOR)
except:
  print(img_name)
```

to locate the potentially corrupted images?

**Comment by aiboys** [comment]
> Can you try:
> 
> ```
> try:
>   with open(img_name, 'rb') as f:
>     img_buff = f.read()
>   img = mmcv.imfrombytes(img_buff, IMREAD_COLOR)
> except:
>   print(img_name)
> ```
> 
> to locate the potentially corrupted images?

I have found the following imgs corrupted:
in sub_121
![image](https://user-images.githubusercontent.com/45069071/160035493-9d05fe1e-c9d1-4084-84c1-bbe5bad6a2a2.png)
I am not sure whether my decompressing meets some mistakes.

**Comment by longshangbang** [comment]
It seems like these images are empty. Probably due to some error in the compression and upload process. Please remove these images.
