### ISSUE TITLE
the address of UnrealEngine is invalid

### ISSUE THREAD

**Issue by Instantnoodles-madman** [Jyouhou/UnrealText#3]
when i tried  to git pull  the UnrealEngine by useing order ''git clone -b 4.22 https://github.com/EpicGames/UnrealEngine.git'' ,it was failed 
repository 'https://github.com/EpicGames/UnrealEngine.git/' not found

**Comment by longshangbang** [comment]
Please refer to this [AirSim documentation](https://microsoft.github.io/AirSim/build_linux/#build-unreal-engine-and-airsim). UE is not a public repo. You need to get registered with Epic.

**Comment by Instantnoodles-madman** [comment]
I have registered with Epic.

**Comment by Instantnoodles-madman** [comment]
I have registered with Epic. the step1 is failed ---git clone -b 4.22 https://github.com/EpicGames/UnrealEngine.git

**Comment by Instantnoodles-madman** [comment]
I have registered with Epic. the step 1 is failed ---git clone -b 4.22 https://github.com/EpicGames/UnrealEngine.git  i thought it is no realted about wether i registered

**Comment by longshangbang** [comment]
You need to link your github account with Epic Games.

**Comment by longshangbang** [comment]
Can you see the Unreal Engine repo in https://github.com/EpicGames ?

**Comment by Instantnoodles-madman** [comment]
yes  I can

**Comment by longshangbang** [comment]
Can you give me the output of "git clone -b 4.22 https://github.com/EpicGames/UnrealEngine.git"?

**Comment by Instantnoodles-madman** [comment]
remote: Repository not found.
fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found

**Comment by Instantnoodles-madman** [comment]
when i tried git clone other project ,i succeed

**Comment by Instantnoodles-madman** [comment]
so ,what to do can reslove this problem

**Comment by longshangbang** [comment]
Can you specify your system configurations? (e.g. ubuntu version)

Have you already configured your github account correctly? 

I just tried to clone it to a new ubuntu system, and it asked for my github username and password. Then it started cloning. 

Can you clone other private Epic repos?

**Comment by Instantnoodles-madman** [comment]
sudo git clone https://github.com/EpicGames/DirectXShaderCompiler.git
Cloning into 'DirectXShaderCompiler'...
remote: Enumerating objects: 58225, done.
Receiving objects: 100% (58225/58225), 46.49 MiB | 567.00 KiB/s, done.
Resolving deltas: 100% (39086/39086), done.
Checking connectivity... done.
Checking out files: 100% (14599/14599), done.


yes， i can git clone https://github.com/EpicGames/DirectXShaderCompiler.git

**Comment by longshangbang** [comment]
DirectXShapeComplier is a public project. Can you try ARTv2 or UnrealTournament which are private?

**Comment by Instantnoodles-madman** [comment]
can you give me the path?

**Comment by longshangbang** [comment]
They can be found under https://github.com/EpicGames : 
https://github.com/EpicGames/UnrealTournament and https://github.com/EpicGames/ARTv2

**Comment by Instantnoodles-madman** [comment]
i cannot open so  it must be failed when i git clone

**Comment by longshangbang** [comment]
I guess it is because you didn't link your github account and epic account. Check my profile: https://github.com/Jyouhou you can see the Epic badge under Organization

**Comment by Instantnoodles-madman** [comment]
ok , i will check other configure ,thank you very much
