### ISSUE TITLE
when i compil UE，it happend wrong

### ISSUE THREAD

**Issue by Instantnoodles-madman** [Jyouhou/UnrealText#6]
Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-4688746-f006827fb0f043339219f8569dbe45f2/023575ba9057aaffd75ea0bd851b2fc6950a9e51': The operation has timed out. (WebException)
but i can download this file,How update dependencies manually?
may you know the reason for this wrong

**Comment by longshangbang** [comment]
Can you give more context of this error? e.g. your environments, what command you executed, etc..

**Comment by Instantnoodles-madman** [comment]
command i executed：
cd UnrealEngine
./Setup.sh

**Comment by longshangbang** [comment]
I didn’t meet similar problems. 

I would suggest that you seek help in UE’s forum or Github repo :)

**Comment by Instantnoodles-madman** [comment]
i think the reason is i don't set proxy
but i don,t know where and how to set when i execute the step- 'mono Engine/Binaries/DotNET/GitDependencies.exe $ARGS'

**Comment by longshangbang** [comment]
I don't know which step you are referring to. Can you give more detail and context?

**Comment by Instantnoodles-madman** [comment]
when  i  compile thr engine ，  execute the step ./Setup.sh，It report  Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-4688746-f006827fb0f043339219f8569dbe45f2/023575ba9057aaffd75ea0bd851b2fc6950a9e51': The operation has timed out. (WebException)
 but  i  set  mono Engine/Binaries/DotNET/GitDependencies.exe $ARGS --proxy="http://..."

**Comment by longshangbang** [comment]
what Is your system (win/ubuntu/mac)?

**Comment by longshangbang** [comment]
BTW, did you follow the AirSim's document to install UE?

**Comment by Instantnoodles-madman** [comment]
i tried both win and ubuntu

**Comment by Instantnoodles-madman** [comment]
i did as the folowing steps:
git clone -b 4.22 --depth 1 https://github.com/EpicGames/UnrealEngine.git  
cd UnrealEngine
./Setup.sh
./GenerateProjectFiles.sh
make
but i failed when i executed ./Setup.sh

**Comment by longshangbang** [comment]
When you open this link 'http://cdn.unrealengine.com/dependencies/UnrealEngine-4688746-f006827fb0f043339219f8569dbe45f2/023575ba9057aaffd75ea0bd851b2fc6950a9e51', can you download this file directly? I can download this file. 

I didn't meet this problem before. I doubt it might be caused by your network connections.

**Comment by Instantnoodles-madman** [comment]
yes ,i can download it directly , i think it is the network's reason ,i need to set proxy,but when   i set mono Engine/Binaries/DotNET/GitDependencies.exe $ARGS --proxy="http://..." , it still failed

**Comment by Instantnoodles-madman** [comment]
i sovled the Dependencies by copy the  files from others,but new error happend   ERROR: Visual Studio 2017 must be installed in order to build this target. 
but i have installed it

**Comment by longshangbang** [comment]
That sounds weird. Do you have gcc/g++/make installed already?

**Comment by Liyucheen** [comment]
I also encountered the same problem. How did you solve it？

**Comment by Liyucheen** [comment]
~/UnrealEngine$ ./Setup.sh
Registering git hooks... (this will override existing ones!)
Fixing inconsistent case in filenames.
Setting up Mono
Checking dependencies (excluding Win32, Win64, Mac, Android)...
Updating dependencies:   0% (0/31077)...
Failed to download 'http://cdn.unrealengine.com/dependencies/3080521-4555593138d749878eace1a85d45da69/02a0f12c2e24355ee396573eb72a2ae8cf84e86a': The request timed out (WebException)
Result: 1
