### ISSUE TITLE
Can I send an image to be the background of synthesis text，and after then, we control the view and light for the synthesis image?

### ISSUE THREAD

**Issue by zhangjx123** [Jyouhou/UnrealText#7]
Can I send an image to be the background of synthesis text，and after then, we control the view and light for the synthesis image?

**Comment by longshangbang** [comment]
Yes you can. Check this: https://github.com/Jyouhou/UnrealText/issues/5

The view & light controls and the image rendering part are independent. You can change the order.

**Comment by zhangjx123** [comment]
OK, and there is an error:ERROR:__init__:205:Can not connect to ('localhost', 9000) when I run: python3 run_generation.py --UnrealProjectName Arch-2 --languages Latin. Is this error caused by my failure to install UE4？I am looking forward to receive your help.Thanks

**Comment by longshangbang** [comment]
You need to launch the game binary first.

**Comment by zhangjx123** [comment]
I think it is a bad news for me. I can only use terminal to work....Do u have some methods to launch the game in terminal?

**Comment by longshangbang** [comment]
Sorry to hear that. I am not sure if the UnrealCV or Unreal Engine supports similar functions.

**Comment by zhangjx123** [comment]
Thanks for your answers. Best wishes!
