### ISSUE TITLE
adout the System environment

### ISSUE THREAD

**Issue by Instantnoodles-madman** [Jyouhou/UnrealText#8]
i have a question this project must run in linux?how to run in windows

**Comment by longshangbang** [comment]
The whole project was developed on a ubuntu machine. 

In order to run it on windows, some modifications are necessary. For example, you need to install the UE and other dependencies in windows.

**Comment by Instantnoodles-madman** [comment]
just install the UE and other dependencies in windows is ok?

**Comment by longshangbang** [comment]
I think so. You should also check UnrealCV's repository, to see if they have any information on using it on Windows.

**Comment by Instantnoodles-madman** [comment]
the  project must relay on visual  studio ,is right?

**Comment by longshangbang** [comment]
I don't think so.
